export const queryKeys = {
  contests: ['contests'] as const,
  scheduledTeasers: ['scheduled-contests-teaser'] as const,
  moderatedContestIds: (userId: string) => ['moderated-contest-ids', userId] as const,
  profileNameStyleCaps: (profileId: string) => ['profile-name-style-caps', profileId] as const,
  myContestSubmissions: (profileId: string) => ['my-contest-submissions', profileId] as const,
  favoriteSoundtrackGames: (profileId: string) => ['favorite-soundtrack-games', profileId] as const,
  adminContest: (contestId: string) => ['admin-contest', contestId] as const,
  contestCore: (slug: string) => ['contest-core', slug] as const,
  contestReveal: (contestId: string) => ['contest-reveal', contestId] as const,
  contestComments: (contestId: string) => ['contest-comments', contestId] as const,
  commentEdits: (commentId: string) => ['comment-edits', commentId] as const,
  gamesCatalog: ['games-catalog'] as const,
  gamePage: (slug: string) => ['game-page', slug] as const,
  tracksPage: (viewerKey: string) => ['tracks-page', viewerKey] as const,
  playersPublic: ['players-public'] as const,
  publicProfile: (username: string) => ['public-profile', username] as const,
  siteHost: ['site-host'] as const,
  authProfile: (userId: string) => ['auth-profile', userId] as const,
  moderatedContests: (userId: string) => ['moderated-contests', userId] as const,
  adminContestsList: ['admin-contests-list'] as const,
  adminGrading: (contestId: string) => ['admin-grading', contestId] as const,
  adminUsers: ['admin-users'] as const,
  adminUser: (userId: string) => ['admin-user', userId] as const,
  adminGame: (gameId: string) => ['admin-game', gameId] as const,
}
